# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 02:29
from __future__ import unicode_literals

import address.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bus_size', models.CharField(choices=[('12', '12 passengers'), ('16', '16 passengers'), ('22', '22 passengers'), ('30', '33 passengers')], max_length=2)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration', models.IntegerField(verbose_name='Number of hours')),
                ('comments', models.CharField(blank=True, max_length=1024, null=True)),
                ('quote_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Reservation')),
                ('email', models.EmailField(max_length=254)),
                ('stripe_id', models.CharField(blank=True, max_length=30)),
                ('charge_amount', models.IntegerField(default=0)),
                ('charge_status', models.CharField(blank=True, max_length=100)),
                ('charge_description', models.CharField(blank=True, max_length=200)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='location_pick_up',
            field=address.models.AddressField(on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
    ]
