# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='location_pick_up',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
