# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20171204_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default='12:00:00'),
            preserve_default=False,
        ),
    ]
