# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20171204_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='0', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bus_size',
            field=models.CharField(choices=[('12', '12 passengers'), ('16', '16 passengers'), ('22', '22 passengers'), ('30', '30 passengers')], max_length=2),
        ),
    ]
