# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20171217_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoResSurvey',
            fields=[
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Reservation')),
                ('reason', models.CharField(choices=[('quotes', "I'm just here to get a quote"), ('prices not competitive', 'I found a lower price somewhere else'), ('service', "I'm not sure if you offer the service I'm looking for."), ('bus', 'I want more info on the bus'), ('prices too high', 'Party buses are too expensive')], max_length=2)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(blank=True, default='19:00', null=True),
        ),
    ]
