# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20171218_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noressurvey',
            name='detail',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(choices=[('bus', 'I want more info on the bus'), ('service', "I'm not sure if you offer the service I'm looking for."), ('quotes', "I'm just here to get a quote"), ('prices too high', 'Party buses are too expensive'), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150),
        ),
    ]
