# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_auto_20171218_1908'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='noressurvey',
            managers=[
                ('surveyed', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('prices not competitive', 'I found a lower price somewhere else'), ('bus', 'I want more info on the bus'), ('quotes', "I'm just here to get a quote"), ('prices too high', 'Party buses are too expensive'), ('service', "I'm not sure if you offer the service I'm looking for")], max_length=150, null=True),
        ),
    ]
