# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_auto_20171219_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('prices too high', 'Party buses are too expensive'), ('bus', 'I want more info on the bus'), ('quotes', "I'm just here to get a quote"), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150, null=True),
        ),
    ]
