# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_auto_20171220_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='nullemail@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('prices too high', 'Party buses are too expensive'), ('bus', 'I want more info on the bus'), ('service', "I'm not sure if you offer the service I'm looking for"), ('quotes', "I'm just here to get a quote"), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150, null=True),
        ),
    ]
