# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20171228_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='bus_size',
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('quotes', "I'm just here to get a quote"), ('prices too high', 'Party buses are too expensive'), ('service', "I'm not sure if you offer the service I'm looking for"), ('bus', 'I want more info on the bus'), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150, null=True),
        ),
    ]
