# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20180102_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Bus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('prices too high', 'Party buses are too expensive'), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices not competitive', 'I found a lower price somewhere else'), ('bus', 'I want more info on the bus'), ('quotes', "I'm just here to get a quote")], max_length=150, null=True),
        ),
    ]
