# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_auto_20180105_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('bus', 'I want more info on the bus'), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices not competitive', 'I found a lower price somewhere else'), ('quotes', "I'm just here to get a quote"), ('prices too high', 'Party buses are too expensive')], max_length=150, null=True),
        ),
    ]
