# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0025_auto_20180105_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('service', "I'm not sure if you offer the service I'm looking for"), ('bus', 'I want more info on the bus'), ('prices too high', 'Party buses are too expensive'), ('quotes', "I'm just here to get a quote"), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150, null=True),
        ),
    ]
