# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0027_auto_20180105_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('quotes', "I'm just here to get a quote"), ('bus', 'I want more info on the bus'), ('prices too high', 'Party buses are too expensive'), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='affiliate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Affiliate'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Driver'),
        ),
    ]
