# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0030_auto_20180110_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('quotes', "I'm just here to get a quote"), ('prices not competitive', 'I found a lower price somewhere else'), ('bus', 'I want more info on the bus'), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices too high', 'Party buses are too expensive')], max_length=150, null=True),
        ),
    ]
