# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0031_auto_20180110_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('paid deposit', 'paid deposit'), ('no deposit', 'no deposit'), ('completed', 'completed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('pending', 'pending'), ('new', 'new')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('prices too high', 'Party buses are too expensive'), ('bus', 'I want more info on the bus'), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices not competitive', 'I found a lower price somewhere else'), ('quotes', "I'm just here to get a quote")], max_length=150, null=True),
        ),
    ]
