# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0032_auto_20180111_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('comments', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='bus',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('bus', 'I want more info on the bus'), ('quotes', "I'm just here to get a quote"), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices too high', 'Party buses are too expensive'), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('no deposit', 'no deposit'), ('completed', 'completed'), ('paid deposit', 'paid deposit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed'), ('new', 'new')], max_length=100, null=True),
        ),
    ]
