# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0036_auto_20180114_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('prices too high', 'Party buses are too expensive'), ('prices not competitive', 'I found a lower price somewhere else'), ('service', "I'm not sure if you offer the service I'm looking for"), ('bus', 'I want more info on the bus'), ('quotes', "I'm just here to get a quote")], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('no deposit', 'no deposit'), ('paid deposit', 'paid deposit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('completed', 'completed'), ('new', 'new')], max_length=100, null=True),
        ),
    ]
