# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0037_auto_20180114_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='noressurvey',
            name='reason',
            field=models.CharField(blank=True, choices=[('bus', 'I want more info on the bus'), ('quotes', "I'm just here to get a quote"), ('prices too high', 'Party buses are too expensive'), ('service', "I'm not sure if you offer the service I'm looking for"), ('prices not competitive', 'I found a lower price somewhere else')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(blank=True, default='5:00 PM', null=True),
        ),
    ]
