# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0040_auto_20180124_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, max_length=30)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('charge_type', models.CharField(blank=True, choices=[('deposit', 'deposit'), ('full payment', 'complete'), ('other', 'other')], max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='noressurvey',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reservation',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='quote_amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='quote_savings',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='new', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'pending'), ('n', 'new'), ('c', 'completed')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='NoResSurvey',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='charge',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.Customer'),
        ),
        migrations.AddField(
            model_name='charge',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Reservation'),
        ),
    ]
